# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# author:
#   name: John
#   email: fantastic.core@gmail.com
  # avatar: /img/avatar.png # 加入你的個人頭像圖片s
  
# social:
#   github: https://github.com/chenchiwang
#   linkedin: https://www.linkedin.com/in/john-wang-5bb70bb3/
  # twitter: https://twitter.com/yourhandle

# theme_skin: "dark" # 如果你想要深色模式


# 基本設置
title: "CCsphere"
description: "Relocation"
baseurl: "" # 如果是根域名，保持空白
url: "https://chenchiwang.github.io" # 你的網站 URL
# 範例：引入 Noto Sans TC 和 Roboto
google_fonts: "Noto+Sans+TC:400,700|Roboto:400,700"
css:
  - "/assets/css/style.css"

# theme: minima # 這是 Jekyll 的默認主題，你可以更換為其他主題
# remote_theme: "mmistakes/minimal-mistakes"
remote_theme: "daattali/beautiful-jekyll"
# remote_theme: "cotes2020/jekyll-theme-chirpy"
# remote_theme: "chesterhow/tale"
# remote_theme: "fongandrew/hydeout"
# remote_theme: "pages-themes/slate"
# remote_theme: "pages-themes/cayman"


# 站點導航
collections:
  blog:
    output: true
  projects:
    output: true
    permalink: /projects/:path/
  pages:
    output: true
    permalink: /pages/:path/

# 分頁和顯示
paginate: 5 # 每頁顯示5篇文章
paginate_path: "/blog/page:num/"

# 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-mermaid

include:
  - favicon.ico
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
